### ISSUE TITLE
System architecture does not match installed version of Python

### ISSUE THREAD

**Issue by nicholsn** [gldnspud/virtualenv-pythonw-osx#4]
I'm using a 64-bit macbook that is running a 32-bit version of EPD. The app bundle generated matches the system architecture rather than the architecture of the installed version of python, resulting in this nasty error when I run pythonw:
```bash
arch: posix_spawnp: /Users/nolan/.virtualenv/bips/Python.app/Contents/MacOS/Python: Bad CPU type in executable
```
Simple fix is just removing the incorrect architecture type from https://github.com/gldnspud/virtualenv-pythonw-osx/blob/master/install_pythonw.py#L100

Or use something like this to check for the installed python version's architecture and then choose the correct architecture to build:
```python
import struct
bits = 8 * struct.calcsize("P")
```

**Comment by matthewryanscott** [comment]
Fixed at https://github.com/gldnspud/virtualenv-pythonw-osx/commit/8ecc0f3cab6493d3e719c62e8ee47ebff7881ed1

(Cleaning up old issues in this repo - thanks again for the patch @nicholsn!)
